Repository DUNE-DAQ/daqconf, pull requests merged in 2022-05, with the labels that each got.

#59 Check that topic name does not duplicate a connection UID
  python/daqconf/core/conf_utils.py
  scripts/daqconf_multiru_gen
Labels: bug

#62 Fix timesync connection in DQM
  python/daqconf/apps/dqm_gen.py
Labels: bug

#70 Eflumerf/topo sort for endpoints
  python/daqconf/apps/dfo_gen.py
  python/daqconf/apps/readout_gen.py
  python/daqconf/core/app.py
  python/daqconf/core/conf_utils.py
  python/daqconf/core/fragment_producers.py
  python/daqconf/core/system.py
  scripts/daqconf_multiru_gen
Labels: bug

#71 Better tracking of publisher and subscriber connectionids to avoid ad…
  python/daqconf/apps/trigger_gen.py
  python/daqconf/core/app.py
  python/daqconf/core/conf_utils.py
  python/daqconf/core/daqmodule.py
Labels: bug

#52 Update to create configurations to readout TP's from FELIX card
  python/daqconf/apps/readout_gen.py
  python/daqconf/apps/tpwriter_gen.py
  python/daqconf/apps/trigger_gen.py
  scripts/daqconf_multiru_gen
Labels: feature

#77 Fix generation with --enable-dqm with topographical sorting
  python/daqconf/apps/dqm_gen.py
  python/daqconf/core/fragment_producers.py
Labels: bug

#78 Change the connections ignored by the topographical sort so that the …
  python/daqconf/apps/dfo_gen.py
Labels: bug

#79 Updated version
  CMakeLists.txt
Labels: version change

#81 Bump version
  CMakeLists.txt
Labels: version change

#83 Bump version
  CMakeLists.txt
Labels: version change
