Repository DUNE-DAQ/daqconf, pull requests merged in 2022-09, with the labels that each got.

#177 Fix ND_LAr detector name hack
  python/daqconf/apps/readout_gen.py
Labels: bug

#178 Eflumerf/pacman fix
  docs/ConfigurationsForCasualUsers.md
  docs/InstructionsForCasualUsers.md
  docs/README.md
  python/daqconf/apps/readout_gen.py
  schema/daqconf/confgen.jsonnet
Labels: bug

#181 Throw an exception when config file is passed but doesn't exist
  scripts/daqconf_multiru_gen
Labels: bug

#180 Remove unneeded -t and -f options, add --enable-dqm
  scripts/daqconf_multiru_gen
Labels: enhancement

#184 Remove deprecated ini files
  scripts/daqconf.ini
  scripts/daqconf_with_swtpg.ini
Labels: maintenance

#186 Fix indentation of confgen.jsonnet
  schema/daqconf/confgen.jsonnet
Labels: maintenance

#185 Update daqconf_full_config.json
  scripts/daqconf_full_config.json
Labels: maintenance

#187 Add printout of defaults from schema to daqconf_multiru_gen -h.
  python/daqconf/core/config_file.py
  schema/daqconf/confgen.jsonnet
  scripts/daqconf_multiru_gen
Labels: documentation

#191 Use appropriate TP SID for datahandler TPSet stream
  python/daqconf/apps/readout_gen.py
Labels: bug

#198 Fix retrieval of hsi_device_name option
  scripts/daqconf_multiru_gen
Labels: bug

#200 Eflumerf/migration doc
  docs/MigratingToNewConfgen.md
  docs/README.md
Labels: documentation

#199 Jbrooke/dtpctrl
  python/daqconf/apps/readout_gen.py
  python/daqconf/core/sourceid.py
  schema/daqconf/confgen.jsonnet
  scripts/daqconf_full_config.json
  scripts/daqconf_multiru_gen
Labels: feature

#209 Sbhuller/readout fix
  python/daqconf/apps/readout_gen.py
Labels: bug

#213 Eflumerf/bump version
  CMakeLists.txt
Labels: version change

#216 Fix issue when running with --debug in readout_gen.py.
  python/daqconf/apps/readout_gen.py
  scripts/daqconf_multiru_gen
Labels: bug

#222 Update app name for fragment_producers check
  python/daqconf/core/fragment_producers.py
Labels: bug

#223 Eflumerf/version bump
  CMakeLists.txt
Labels: version change
