Repository DUNE-DAQ/daqconf, pull requests merged in 2022-11, with the labels that each got.

#238 Sort link lists to ensure that they are mapped correctly
  python/daqconf/apps/readout_gen.py
Labels: bug

#246 Update version to v5.5.4
  CMakeLists.txt
Labels: version change

#247 Eflumerf/merge patches
  CMakeLists.txt
  python/daqconf/apps/readout_gen.py
  scripts/daqconf_multiru_gen
Labels: maintenance

#248 Allow setting the Latency Buffer NUMA conf on a per-RU basis. Allow for
  python/daqconf/apps/readout_gen.py
  schema/daqconf/confgen.jsonnet
  scripts/daqconf_multiru_gen
Labels: bug

#254 Add option to configure DataStore mode
  python/daqconf/apps/dataflow_gen.py
  schema/daqconf/confgen.jsonnet
  scripts/daqconf_multiru_gen
Labels: enhancement

#257 patch to generate appropriate firmware tp configurations
  python/daqconf/apps/readout_gen.py
Labels: feature
