Repository DUNE-DAQ/daqconf, pull requests merged in 2022-10, with the labels that each got.

#225 Update daqconf_full_config.json using output of daqconf_multiru_gen -h.
  config/daqconf_full_config.json
  docs/ConfigurationsForCasualUsers.md
  docs/InstructionsForCasualUsers.md
  docs/README.md
Labels: bug, documentation

#227 Eflumerf/numa config
  config/daqconf_full_config.json
  python/daqconf/apps/readout_gen.py
  schema/daqconf/confgen.jsonnet
  scripts/daqconf_multiru_gen
Labels: enhancement

#228 Sbhuller/dunedaq v3.2.0 rc patch
  python/daqconf/apps/readout_gen.py
Labels: bug

#230 Fix location of FakeCardReader in readout_gen's logic.
  python/daqconf/apps/readout_gen.py
Labels: bug

#231 Update version number
  CMakeLists.txt
Labels: version change
