Repository DUNE-DAQ/daqconf, pull requests merged in 2024-03, with the labels that each got.

#431 Added an offline_data_stream config param to the detector daqconf group and the dataflow datastore parameters
  python/daqconf/apps/dataflow_gen.py
  schema/daqconf/detectorgen.jsonnet
Labels: deliverable subtask

#434 Added tardy_tp_quiet_time_at_start_sec...
  python/daqconf/apps/readout_gen.py
Labels: miscellaneous deliverable

#433 Add TPG configuration parameters
  python/daqconf/apps/readout_gen.py
Labels: enhancement, miscellaneous deliverable

#438 New DBSCAN Configurables
  config/daqconf_full_config.json
  schema/daqconf/triggergen.jsonnet
Labels: maintenance, miscellaneous deliverable

#436 New ChannelDistance Algorithm
  config/daqconf_full_config.json
  schema/daqconf/triggergen.jsonnet
Labels: enhancement, miscellaneous deliverable

#439 New BundleN Configurable
  config/daqconf_full_config.json
  schema/daqconf/triggergen.jsonnet
Labels: maintenance, miscellaneous deliverable

#442 add back in tpg threshold configuration
  python/daqconf/apps/readout_gen.py
Labels: miscellaneous deliverable

#444 Update docker image
  schema/daqconf/bootgen.jsonnet
Labels: miscellaneous deliverable

#441 CTB: Trigger integration
  config/daqconf_full_config.json
  python/daqconf/apps/trigger_gen.py
  schema/daqconf/triggergen.jsonnet
Labels: miscellaneous deliverable

#445 tmp fix: update hsievents connections for individual tc makers
  python/daqconf/apps/fake_hsi_gen.py
  python/daqconf/apps/hsi_gen.py
Labels: miscellaneous deliverable

#440 Adde TPStreamWriter configuration parameters
  python/daqconf/apps/tpwriter_gen.py
  schema/daqconf/dataflowgen.jsonnet
Labels: miscellaneous deliverable
