Repository DUNE-DAQ/daqconf, pull requests merged in 2024-07, with the labels that each got.

#478 Adding opmon interval as a boot option
  python/daqconf/core/conf_utils.py
  schema/daqconf/bootgen.jsonnet
Labels: good first issue, miscellaneous deliverable

#481 Removed LB Intrinsic Allocator.
  python/daqconf/apps/readout_gen.py
Labels: bug

#443 update the crt dro to have an input directory option, and other fixes
  python/daqconf/core/conf_utils.py
  python/daqconf/detreadoutmap.py
  schema/daqconf/detreadoutmap.jsonnet
Labels: miscellaneous deliverable
